export const BOOKS: Book[] = [
  {
    name: "In Search Of Excellence",
    author: "Thomas J. Peters, Robert H. Waterman Jr.",
    genre: "Business",
    status: "Read",
    dateStarted: "17/04/2023",
    dateCompleted: "21/05/2023",
  },
  {
    name: "A Clockwork Orange",
    author: "Anthony Burgess",
    genre: "Fiction",
    status: "Read",
    dateStarted: "10/04/2023",
    dateCompleted: "14/04/2023",
  },
  {
    name: "The Hitchiker's Guide to the Galaxy",
    author: "Douglas Adams",
    genre: "Science Fiction",
    status: "Read",
    dateStarted: "08/04/2023",
    dateCompleted: "09/04/2023",
  },
  {
    name: "Project Hail Mary",
    author: "Andy Weir",
    genre: "Science Fiction",
    status: "Read",
    dateStarted: "04/04/2023",
    dateCompleted: "08/04/2023",
  },
  {
    name: "The End of Faith: Religion, Terror, and the Future of Reason",
    author: "Sam Harris",
    genre: "Nonfiction",
    status: "Read",
    dateStarted: "24/03/2023",
    dateCompleted: "04/04/2023",
  },
  {
    name: "The God Delusion",
    author: "Richard Dawkins",
    genre: "Nonfiction",
    status: "Read",
    dateStarted: "13/03/2023",
    dateCompleted: "24/03/2023",
  },
  {
    name: "God Is Not Great: How Religion Poisons Everything",
    author: "Christopher Hitchens",
    genre: "Nonfiction",
    status: "Read",
    dateStarted: "10/03/2023",
    dateCompleted: "13/03/2023",
  },
  {
    name: "Fahrenheit 451",
    author: "Ray Bradbury",
    genre: "Science Fiction",
    status: "Read",
    dateStarted: "07/03/2023",
    dateCompleted: "10/03/2023",
  },
  {
    name: "It's OK to be Angry About Capitalism",
    author: "Bernie Sanders",
    genre: "Politics",
    status: "Read",
    dateStarted: "01/03/2023",
    dateCompleted: "04/03/2023",
  },
  {
    name: "Built to Last: Successful Habits of Visionary Companies",
    author: "James C. Collins, Jerry I. Porras",
    genre: "Business",
    status: "Read",
    dateStarted: "23/02/2023",
    dateCompleted: "28/02/2023",
  },
  {
    name: "Thinking in Systems: A Primer",
    author: "Donella H. Meadows and Diana Wright",
    genre: "Nonfiction",
    status: "Read",
    dateStarted: "20/02/2023",
    dateCompleted: "23/02/2023",
  },
  {
    name: "The Dawn of Everything",
    author: "David Greaber and David Wengrow",
    genre: "Nonfiction",
    status: "Read",
    dateStarted: "13/01/2023",
    dateCompleted: "02/02/2023",
  },
  {
    name: "The Hero of Ages",
    author: "Brandon Sanderson",
    genre: "Fantasy",
    status: "Read",
    dateStarted: "09/01/2023",
    dateCompleted: "12/01/2023",
  },
  {
    name: "The Well of Ascension",
    author: "Brandon Sanderson",
    genre: "Fantasy",
    status: "Read",
    dateStarted: "05/01/2023",
    dateCompleted: "08/01/2023",
  },
  {
    name: "Stolen Focus",
    author: "Johann Hari",
    genre: "Nonfiction",
    status: "Read",
    dateStarted: "01/01/2023",
    dateCompleted: "03/01/2023",
  },
  {
    name: "The Final Empire",
    author: "Brandon Sanderson",
    genre: "Fantasy",
    status: "Read",
    dateStarted: "26/12/2022",
    dateCompleted: "01/01/2023",
  },
  {
    name: "The Pragmatic Programmer: From Journeyman to Master",
    author: "Andy Hunt, Dave Thomas",
    genre: "Programming",
    status: "Read",
    dateStarted: "05/09/2020",
    dateCompleted: "19/02/2023",
  },
  {
    name: "The Black Swan: The Impact of the Highly Improbable",
    author: "Nassim Nicholas Taleb",
    genre: "Nonfiction",
    status: "Read",
    dateStarted: "26/09/2022",
    dateCompleted: "24/12/2022",
  },
  {
    name: "Wordslut: A Feminist Guide to Taking Back the English Language",
    author: "Amanda Montell",
    genre: "Nonfiction",
    status: "Read",
    dateStarted: "12/09/2022",
    dateCompleted: "25/09/2022",
  },
  {
    name: "Steve Jobs",
    author: "Walter Isaacson",
    genre: "Biography",
    status: "Read",
    dateStarted: "24/07/2022",
    dateCompleted: "11/09/2022",
  },
  {
    name: "Brave New World",
    author: "Aldous Huxley",
    genre: "Fiction",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2022",
  },
  {
    name: "Modern Conspiracies in America: Separating Fact from Fiction",
    author: "Michael D. Gambone",
    genre: "Nonfiction",
    status: "Read",
    dateStarted: "",
    dateCompleted: "26/06/2022",
  },
  {
    name: "Cultish: The Language of Fanaticism",
    author: "Amanda Montell",
    genre: "Nonfiction",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2022",
  },
  {
    name: "How to Lie with Statistics",
    author: "Darrell Huff",
    genre: "Mathmatics",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2022",
  },
  {
    name: "The Alchemist",
    author: "Paulo Coelho",
    genre: "Philosophy",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2022",
  },
  {
    name: "A Promised Land",
    author: "Barack Obama",
    genre: "Politics",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2022",
  },
  {
    name: "The Subtle Art of Not Giving a F*ck: A Counterintuitive Approach to Living a Good Life",
    author: "Mark Manson",
    genre: "Self Help",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2022",
  },
  {
    name: "Peril",
    author: "Bob Woodward, Robert Costa",
    genre: "Politics",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2022",
  },
  {
    name: "21 Lessons for the 21st Century",
    author: "Yuval Noah Harari",
    genre: "Sociology",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2022",
  },
  {
    name: "The Anthropocene Reviewed",
    author: "John Green",
    genre: "Short Stories",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2022",
  },
  {
    name: "Clean Code",
    author: "Robert C. Martin",
    genre: "Programming",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2021",
  },
  {
    name: "Rage",
    author: "Bob Woodward",
    genre: "Politics",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2021",
  },
  {
    name: "On Having No Head",
    author: "Douglas E. Harding",
    genre: "Spirituality",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2021",
  },
  {
    name: "The Lord of the Rings The Return of the King",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2021",
  },
  {
    name: "The Lord of the Rings The Two Towers",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2021",
  },
  {
    name: "Lord of the Rings the Fellowship of the Ring",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2021",
  },
  {
    name: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2021",
  },
  {
    name: "12 Rules for Life: An Antidote to Chaos",
    author: "Jordan B. Peterson",
    genre: "Self Help",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2021",
  },
  {
    name: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    genre: "History",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2021",
  },
  {
    name: "Propaganda",
    author: "Edward L. Bernays",
    genre: "Psychology",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2021",
  },
  {
    name: "Fear: Trump in the White House",
    author: "Bob Woodward",
    genre: "Politics",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2021",
  },
  {
    name: "Animal Farm",
    author: "George Orwell",
    genre: "Politics",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2021",
  },
  {
    name: "1984",
    author: "George Orwell",
    genre: "Politics",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2021",
  },
  {
    name: "Manufacturing Consent",
    author: "Edward S. Herman, Noam Chomsky",
    genre: "Politics",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2021",
  },
  {
    name: "The Power of Now",
    author: "Eckhart Tolle",
    genre: "Spirituality",
    status: "Read",
    dateStarted: "",
    dateCompleted: "2021",
  },
];
