name: E2E Tests
on:
  push:
    branches: [main]
jobs:
  e2e_tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm@10.7.1

      - name: Install Dependancies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm dlx playwright@1.53.2 install --with-deps

      - name: Run Playwright E2E Tests
        run: pnpm run test:e2e
